{% set name = "pidcalib2" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidcalib2-{{ version }}.tar.gz
  sha256: 5c68be377c783a51c82d3ef226df09044e93c17f9ea492cd7affc1c70546d488

build:
  number: 0
  noarch: python
  entry_points:
    - pidcalib2.make_eff_hists = pidcalib2.make_eff_hists:main
    - pidcalib2.ref_calib = pidcalib2.ref_calib:main
    - pidcalib2.merge_trees = pidcalib2.merge_trees:main
    - pidcalib2.pklhisto2root = pidcalib2.pklhisto2root:main
    - pidcalib2.plot_calib_distributions = pidcalib2.plot_calib_distributions:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm >=3.4
    - setuptools >=30.3.0
    - wheel
  run:
    - boost-histogram
    - lb-telemetry
    - logzero
    - numpy
    - pandas
    - python >=3.7
    - tqdm
    - uproot >=4.2.1
    - uproot3
    - matplotlib-base
    - mplhep
    - xrootd >=5.2
    - apd

test:
  imports:
    - pidcalib2
    - pidcalib2.tests
  commands:
    # Fails as there is a dependency on XRootD 5.2 but that's only available for CentOS 7+
    # - pip check
    - pidcalib2.make_eff_hists --help
    # Can't be tested without installing ROOT
    # - pidcalib2.ref_calib --help
    # - pidcalib2.merge_trees --help
    # - pidcalib2.pklhisto2root --help
    # - pidcalib2.plot_calib_distributions --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-rta/pidcalib2
  summary: A set of tools for estimating LHCb PID efficiencies
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - seophine
    - dcervenkov
    - chrisburr
